<a href="https://colab.research.google.com/github/kgpark88/ai-summary/blob/main/02_AutoGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

출처 : https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html

In [1]:
import torch

tensor를 생성하고 requires_grad=True 를 설정하여 연산을 기록합니다.

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


tensor에 연산을 수행합니다:

In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y 는 연산의 결과로 생성된 것이므로 grad_fn 을 갖습니다.

In [4]:
print(y.grad_fn)

y 에 다른 연산을 수행합니다.

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_( ... ) 는 기존 Tensor의 requires_grad 값을 바꿔치기 (in-place)하여 변경합니다.   
입력값이 지정되지 않으면 기본값은 False 입니다.

In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### Gradient
이제 역전파(backprop)를 해보겠습니다.   
out 은 하나의 스칼라 값만 갖고 있기 때문에, out.backward() 는 out.backward(torch.tensor(1.)) 과 동일합니다.

In [7]:
out.backward()

변화도 d(out)/dx를 출력합니다.

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
