# Numpy 기본

## Numpy 설치    
    pip install numpy
    !pip install numpy

NumPy 라이브러리 임포트

In [1]:
import numpy as np

파이썬 List로 Numpy Array를 생성합니다.

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 내장 메서드(Built-in Method)

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

0 또는 1 array 생성

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
지정된 범위내에서 균등한 간격의 숫자를 반환합니다.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

단위 행렬(identity matrix)을 생성합니다.

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy는 난수 배열을 만드는 많은 방법을 가지고 있습니다 :

### rand
  0부터 1사이의 균일 분포에서 난수 matrix array 생성

In [15]:
np.random.rand(2)

array([0.65975655, 0.70318641])

In [16]:
np.random.rand(5,5)

array([[0.02232422, 0.43230286, 0.53863438, 0.27059672, 0.84072838],
       [0.97902201, 0.28889825, 0.49984617, 0.48694756, 0.47914101],
       [0.05702412, 0.98786407, 0.64993643, 0.09789868, 0.3178407 ],
       [0.77669816, 0.3380982 , 0.18688264, 0.1102515 , 0.81129064],
       [0.08524559, 0.0848354 , 0.23257764, 0.62790469, 0.50168051]])

### randn

 가우시안 표준 정규 분포에서 난수 matrix array 생성

In [17]:
np.random.randn(2)

array([-0.97475278, -0.38825575])

In [18]:
np.random.randn(5,5)

array([[ 1.57381807, -1.93417958, -1.12345572,  0.13646328,  2.4113335 ],
       [-0.2402955 , -1.40951232,  0.83278371, -0.67723755, -0.54189495],
       [-1.07197619,  1.23867073,  1.19366453,  0.56685162, -1.04681874],
       [ 0.15312419,  0.76431075, -0.31276942, -0.73034105,  0.68705065],
       [-1.5771968 ,  1.84344605,  0.7968852 , -1.14558935, -0.46467439]])

### randint
(시작, n-1) 사이의 랜덤숫자

In [19]:
np.random.randint(1,100)

65

In [20]:
np.random.randint(1,100,10)

array([58, 88, 11,  8, 35, 90, 76,  1, 78, 37])

## Array Attributes and Methods

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([44, 15, 39, 28, 17,  9, 41, 45, 34, 38])

## Reshape
shape 변경

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

In [25]:
ranarr

array([44, 15, 39, 28, 17,  9, 41, 45, 34, 38])

In [26]:
ranarr.max()

45

In [27]:
ranarr.argmax()

7

In [28]:
ranarr.min()

9

In [29]:
ranarr.argmin()

5

## Shape

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape

(25, 1)

### dtype

배열에 있는 오브젝트의 데이터 타입 확인

In [36]:
arr.dtype

dtype('int32')

# NumPy Indexing, Selection

In [37]:
#Creating sample array
arr = np.arange(0,11)

In [38]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# index 위치의 값
arr[8]

8

In [40]:
# range 범위내의 값
arr[1:5]

array([1, 2, 3, 4])

## Indexing a 2D array (matrices)

In [41]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [43]:
# Getting individual element value
arr_2d[1][0]

20

In [44]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Selection

In [46]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr>4

In [49]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy 연산

In [53]:
arr = np.arange(0,10)

In [54]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [56]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
arr/arr

c:\users\danny\.conda\envs\tfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
1/arr

c:\users\danny\.conda\envs\tfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [59]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [60]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [61]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [62]:
np.max(arr) #same as arr.max()

9

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [64]:
np.log(arr)

c:\users\danny\.conda\envs\tfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])