<a href="https://colab.research.google.com/github/kgpark88/ai-summary/blob/main/06_02_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형 회귀(Linear Regression)

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
X = np.arange(50).reshape((5, 10))
y = range(5)

In [3]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [4]:
list(y)

[0, 1, 2, 3, 4]

### Train Test 데이터셋 분할¶

In [5]:
 X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)

In [6]:
X_train

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [7]:
y_train

[2, 0, 3]

In [8]:
y_test

[1, 4]

### 모델 학습

In [9]:
model = LinearRegression()

In [10]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### 회귀 예측

In [11]:
predictions = model.predict(X_test)

In [12]:
predictions

array([1., 4.])